### ISSUE TITLE
Use latest extended version?

### ISSUE THREAD

**Issue by jasikpark** [klakegg/actions-hugo#2]
Is there a way I could set this up to automatically test my site against the latest version of hugo? I need GitInfo, so as I gathered from `klakegg/docker-hugo` I need to use the extended version, but I would really like to just test against the latest version without needing to manually update the pinned version I am using. 

https://github.com/jasikpark/jasik-xyz/blob/master/.github/workflows/hugo.yml
```yml

name: Hugo

on:
  schedule:
    # runs daily at 3am
    - cron: '0 3 * * *'
  push:

jobs:
  build:
    strategy:
      matrix:
        image: [busybox, alpine]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        image: ${{ matrix.image }}
```

I simply removed the versions option so that it will use the latest version, but it's not clear how to use the latest extended version... I would really appreciate your help!!

Also thanks so much for creating this action -- it was really helpful.

**Comment by jasikpark** [comment]
I have solved my own problem by reading https://hub.docker.com/r/klakegg/hugo

```yaml
name: Hugo

on:
  schedule:
    # runs daily at 3am
    - cron: '0 3 * * *'
  push:

jobs:
  build:
    strategy:
      matrix:
        image: [ext-alpine, latest-ext]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        image: ${{ matrix.image }}
```
