### ISSUE TITLE
If you update the actions/checkout to v2, here's the correct settings

### ISSUE THREAD

**Issue by jasikpark** [klakegg/actions-hugo#3]
https://github.com/actions/checkout/issues/149

I tried to use this action with percy-snapshot, and I ended up with .GitInfo.Date returning the wrong info, since `checkout@v2` does a shallow clone, which apparently doesn't include the file history. 

using 

```yml
uses: actions/checkout@v2
  with:
    fetch-depth: 0
```

fixed the problem for me. my new Percy CI config looks like 

```yml
name: Percy
on:
  push:
    branches:
    - "master"
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Hugo
        uses: klakegg/actions-hugo@1.0.0
        with:
          image: latest-ext
      - name: Percy
        uses: percy/snapshot-action@v0.1.1
        with:
          build-directory: "public"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```
